Primavera.NET.Web/Controllers/AdminUsersController.cs
namespace Primavera.NET.Web.Controllers
{
    #region Usings
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using Primavera.NET.Data.Models;
    using Primavera.NET.Data.UnitOfWork;
    using Primavera.NET.Framework;
    using Primavera.NET.Localization;
    using Primavera.NET.Web.Models;

    #endregion

    [MvcAuthorize(Roles = "Admin")]
    public class AdminUsersController : ControllerBase
    {
        #region Private variables

        private readonly IMapper mapper;

        private readonly IEventsBus eventBus;
        #endregion

        #region Constructors
        public AdminUsersController(IUnitOfWork unitOfWork, INotificationService notificationService, IMapper mapper, IEventsBus eventBus)
            : base(unitOfWork, notificationService)
        {
            ValidationHelper.IsNotNull(mapper, "mapper");
            ValidationHelper.IsNotNull(eventBus, "eventBus");

            this.mapper = mapper;
            this.eventBus = eventBus;
        }
        #endregion

        #region Methods (actions)

        public ActionResult Index()
        {
            var users = this.UnitOfWork.Users.GetAll();
            var usersRoles = this.UnitOfWork.Roles.GetBy(users.Select(g => g.Id));

            var items = this.mapper.Map<UserModel, AdminUsersItemViewModel>(users);

            foreach (var loopItem in items)
            {
                IList<RoleModel> roles;
                if (usersRoles.TryGetValue(loopItem.Id, out roles))
                {
                    loopItem.Roles.AddRange(roles.Select(g => g.RoleType));
                }
            }

            var model = new AdminUsersIndexViewModel(items);

            this.InitalizeViewModel(model);

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Delete(int userId)
        {
            if (userId == this.User.CustomIdentity.UserId)
            {
                this.NotificationService.Error(Strings.StringYouCannotDeleteYourSelf.Dot());
                return this.RedirectToAction("Index");
            }          

            this.UnitOfWork.Roles.RemoveUserFromAllRoles(userId);
            UserModel userModel = this.UnitOfWork.Users.GetBy(userId);

            if (userModel == null)
            {
                return this.RedirectResourceNotFound();
            }

            this.UnitOfWork.Users.Delete(userModel);
            this.UnitOfWork.SaveChanges();

            this.eventBus.RaiseOnUserDisconnectRequested(this, new OnUserDisconnectRequestedEventArgs(userId));
            this.eventBus.RaiseOnUsersListReloadRequested(this, EventArgs.Empty);

            this.NotificationService.Information(Strings.StringTheUserHasBeenDeleted.Dot());
            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int userId)
        {
            UserModel userModel = this.UnitOfWork.Users.GetBy(userId);

            if (userModel == null)
            {
                return this.RedirectResourceNotFound();
            }

            AdminUsersItemViewModel model = this.mapper.Map<AdminUsersItemViewModel>(userModel);
            var roleModels = this.UnitOfWork.Roles.GetBy(userId);
            model.Roles.AddRange(roleModels.Select(g => g.RoleType));

            this.InitalizeViewModel(model);

            return this.View(model);
        }

        [HttpPost]
        public ActionResult Edit(AdminUsersItemViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.NotificationService.Error(Strings.StringSomeFieldsAreNotFilledCorrectly.Dot());
            }

            if (model.Id == this.User.CustomIdentity.UserId && !model.Roles.Contains(RoleType.Admin))
            {
                this.NotificationService.Error(Strings.StringYouCannotChangeYourXRole.FormatText(RoleType.Admin).Dot());
                this.ModelState.AddModelError<AdminUsersItemViewModel>(g => g.Roles, string.Empty.Space());
            }

            UserModel userWithSameNickname = this.UnitOfWork.Users.GetByEmailOrNickname(string.Empty, model.Nickname);
            if (userWithSameNickname != null && userWithSameNickname.Id != model.Id)
            {
                this.ModelState.AddModelError<AdminUsersItemViewModel>(g => g.Nickname, Strings.StringThisNicknameIsNotUnique.Dot());
            }
            
            if (!this.ModelState.IsValid)
            {
                this.NotificationService.Error(Strings.StringSomeFieldsAreNotFilledCorrectly.Dot());
                this.InitalizeViewModel(model);
                return this.View(model);
            }

            UserModel user = this.UnitOfWork.Users.GetBy(model.Id);

            if (user == null)
            {
                return this.RedirectResourceNotFound();
            }

            user.Nickname = model.Nickname;
            user.StatusMessage = model.StatusMessage;
            
            this.UnitOfWork.Users.Update(user);
            this.UnitOfWork.Roles.RemoveUserFromAllRoles(user.Id);
            this.UnitOfWork.Users.AddRoles(user.Id, model.Roles.Distinct());
            this.UnitOfWork.SaveChanges();

            this.eventBus.RaiseOnUsersListReloadRequested(this, EventArgs.Empty);

            this.NotificationService.Information(Strings.StringTheUserHasBeenChanged.Dot());

            return this.RedirectToAction("Index");
        }
        #endregion
    }
}

Primavera.NET.Web/Views/AdminUsers/Edit.cshtml
@using Primavera.NET.Localization
@model Primavera.NET.Web.Models.AdminUsersItemViewModel

@{
    ViewBag.Title = Strings.StringEdit;
}

@using (Html.BeginForm("Edit", "AdminUsers", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(g => g.Nickname, Strings.StringNickname, new { @class = "col-sm-3 control-label" })

        <div class="col-sm-6">
            @Html.TextBoxFor(model => model.Nickname, new { @class = "form-control", placeholder = Strings.StringNickname, required = true })
            @Html.ValidationMessageFor(model => model.Nickname)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(g => g.StatusMessage, Strings.StringStatusMessage, new { @class = "col-sm-3 control-label" })

        <div class="col-sm-6">
            @Html.TextBoxFor(model => model.StatusMessage, new { @class = "form-control", placeholder = Strings.StringStatusMessage })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(g => g.Roles, Strings.StringRoles, new { @class = "col-sm-3 control-label" })

        <div class="col-sm-6">
            @Html.ListBoxFor(model => model.Roles, new SelectList(Model.AvailableRoles), new { @class = "form-control", placeholder = Strings.StringStatusMessage, required = false })
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <input type="submit" class="btn btn-default" value="@Strings.StringSave" />
            @Html.ActionLink(Strings.StringCancel, "Index", "AdminUsers", null, new { @class = "btn" })
        </div>
    </div>

    @Html.HiddenFor(g => g.Id)
    @Html.HiddenFor(g => g.Email)
}

Primavera.NET.Web/Views/AdminUsers/Index.cshtml
@using Antlr.Runtime.Tree
@using Primavera.NET.Framework
@using Primavera.NET.Localization
@model Primavera.NET.Web.Models.AdminUsersIndexViewModel

@{
    ViewBag.Title = Strings.StringUsersManagement;
}

<section class="usersmanagement">
    <table class="table table-hover">
        <thead>
            <tr>
                <th></th>
                <th>@Strings.StringNickname</th>
                <th>@Strings.StringEmail</th>
                <th>@Strings.StringStatusMessage</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var loopUser in this.Model.Users)
            {
                <tr>
                    <td>@loopUser.Id</td>
                    <td>@loopUser.Nickname</td>
                    <td>@loopUser.Email</td>
                    <td>@loopUser.StatusMessage</td>
                    <td>@Html.ActionLink(Strings.StringEdit, "Edit", new { userId = loopUser.Id }, new { @class = "btn btn-primary" })</td>
                    <td>@Html.ActionLink(Strings.StringDelete, "Delete", new { userId = loopUser.Id }, new { @class = "btn btn-danger", onclick = "return confirm(\"{0}\");".FormatText(Strings.StringAreYouSureYouWantToDeleteUserX.FormatText(loopUser.Nickname).Question()) })</td>
                </tr>
            }
        </tbody>
    </table>
</section>